name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: bash build.sh
    - name: Publish the Docker image
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: bash publish.sh
